package com.guo.technologyforum.dao.mapper.generateMapper;

import com.guo.technologyforum.dao.entity.AnnounceUser;
import com.guo.technologyforum.dao.entity.AnnounceUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface AnnounceUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    long countByExample(AnnounceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    int deleteByExample(AnnounceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    int insert(AnnounceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    int insertSelective(AnnounceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    List<AnnounceUser> selectByExampleWithRowbounds(AnnounceUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    List<AnnounceUser> selectByExample(AnnounceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    AnnounceUser selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AnnounceUser record, @Param("example") AnnounceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AnnounceUser record, @Param("example") AnnounceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AnnounceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AnnounceUser record);
}