package com.guo.technologyforum.dao.mapper.generateMapper;

import com.guo.technologyforum.dao.entity.Announce;
import com.guo.technologyforum.dao.entity.AnnounceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface AnnounceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    long countByExample(AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int deleteByExample(AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int insert(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int insertSelective(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    List<Announce> selectByExampleWithBLOBsWithRowbounds(AnnounceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    List<Announce> selectByExampleWithBLOBs(AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    List<Announce> selectByExampleWithRowbounds(AnnounceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    List<Announce> selectByExample(AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    Announce selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Announce record, @Param("example") AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Announce record, @Param("example") AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Announce record, @Param("example") AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announce
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Announce record);
}