package com.guo.technologyforum.dao.mapper.generateMapper;

import com.guo.technologyforum.dao.entity.KeepNode;
import com.guo.technologyforum.dao.entity.KeepNodeExample;
import com.guo.technologyforum.dao.entity.KeepNodeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface KeepNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    long countByExample(KeepNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    int deleteByExample(KeepNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(KeepNodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    int insert(KeepNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    int insertSelective(KeepNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    List<KeepNode> selectByExampleWithRowbounds(KeepNodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    List<KeepNode> selectByExample(KeepNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    KeepNode selectByPrimaryKey(KeepNodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KeepNode record, @Param("example") KeepNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KeepNode record, @Param("example") KeepNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KeepNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_node
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KeepNode record);
}