package com.guo.technologyforum.dao.mapper.generateMapper;

import com.guo.technologyforum.dao.entity.KeepTheme;
import com.guo.technologyforum.dao.entity.KeepThemeExample;
import com.guo.technologyforum.dao.entity.KeepThemeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface KeepThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    long countByExample(KeepThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    int deleteByExample(KeepThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(KeepThemeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    int insert(KeepTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    int insertSelective(KeepTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    List<KeepTheme> selectByExampleWithRowbounds(KeepThemeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    List<KeepTheme> selectByExample(KeepThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    KeepTheme selectByPrimaryKey(KeepThemeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KeepTheme record, @Param("example") KeepThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KeepTheme record, @Param("example") KeepThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KeepTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keep_theme
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KeepTheme record);
}