package com.guo.technologyforum.dao.mapper.generateMapper;

import com.guo.technologyforum.dao.entity.ThemeClass;
import com.guo.technologyforum.dao.entity.ThemeClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface ThemeClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    long countByExample(ThemeClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    int deleteByExample(ThemeClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    int insert(ThemeClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    int insertSelective(ThemeClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    List<ThemeClass> selectByExampleWithRowbounds(ThemeClassExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    List<ThemeClass> selectByExample(ThemeClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    ThemeClass selectByPrimaryKey(Integer nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ThemeClass record, @Param("example") ThemeClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ThemeClass record, @Param("example") ThemeClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ThemeClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThemeClass record);
}