package com.guo.technologyforum.dao.mapper.generateMapper;

import com.guo.technologyforum.dao.entity.UserBlock;
import com.guo.technologyforum.dao.entity.UserBlockExample;
import com.guo.technologyforum.dao.entity.UserBlockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface UserBlockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    long countByExample(UserBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    int deleteByExample(UserBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(UserBlockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    int insert(UserBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    int insertSelective(UserBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    List<UserBlock> selectByExampleWithRowbounds(UserBlockExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    List<UserBlock> selectByExample(UserBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    UserBlock selectByPrimaryKey(UserBlockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserBlock record, @Param("example") UserBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserBlock record, @Param("example") UserBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_block
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBlock record);
}