package com.guo.technologyforum.dao.mapper.generateMapper;

import com.guo.technologyforum.dao.entity.UserRelation;
import com.guo.technologyforum.dao.entity.UserRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface UserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    long countByExample(UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    int deleteByExample(UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    int insert(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    int insertSelective(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    List<UserRelation> selectByExampleWithRowbounds(UserRelationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    List<UserRelation> selectByExample(UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    UserRelation selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserRelation record, @Param("example") UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserRelation record, @Param("example") UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRelation record);
}