package com.guo.technologyforum.dao.mapper.generateMapper;

import com.guo.technologyforum.dao.entity.User_Right;
import com.guo.technologyforum.dao.entity.User_RightExample;
import com.guo.technologyforum.dao.entity.User_RightKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface User_RightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    long countByExample(User_RightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    int deleteByExample(User_RightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(User_RightKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    int insert(User_Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    int insertSelective(User_Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    List<User_Right> selectByExampleWithRowbounds(User_RightExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    List<User_Right> selectByExample(User_RightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    User_Right selectByPrimaryKey(User_RightKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") User_Right record, @Param("example") User_RightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") User_Right record, @Param("example") User_RightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User_Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_right
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User_Right record);
}