package com.guo.technologyforum.dao.entity;

import java.util.Date;

public class Announce {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_announce.n_id
     *
     * @mbg.generated
     */
    private Long nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_announce.n_sender_user_id
     *
     * @mbg.generated
     */
    private Long nSenderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_announce.d_create_time
     *
     * @mbg.generated
     */
    private Date dCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_announce.c_content
     *
     * @mbg.generated
     */
    private String cContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_announce.n_id
     *
     * @return the value of t_announce.n_id
     *
     * @mbg.generated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_announce.n_id
     *
     * @param nId the value for t_announce.n_id
     *
     * @mbg.generated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_announce.n_sender_user_id
     *
     * @return the value of t_announce.n_sender_user_id
     *
     * @mbg.generated
     */
    public Long getnSenderUserId() {
        return nSenderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_announce.n_sender_user_id
     *
     * @param nSenderUserId the value for t_announce.n_sender_user_id
     *
     * @mbg.generated
     */
    public void setnSenderUserId(Long nSenderUserId) {
        this.nSenderUserId = nSenderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_announce.d_create_time
     *
     * @return the value of t_announce.d_create_time
     *
     * @mbg.generated
     */
    public Date getdCreateTime() {
        return dCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_announce.d_create_time
     *
     * @param dCreateTime the value for t_announce.d_create_time
     *
     * @mbg.generated
     */
    public void setdCreateTime(Date dCreateTime) {
        this.dCreateTime = dCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_announce.c_content
     *
     * @return the value of t_announce.c_content
     *
     * @mbg.generated
     */
    public String getcContent() {
        return cContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_announce.c_content
     *
     * @param cContent the value for t_announce.c_content
     *
     * @mbg.generated
     */
    public void setcContent(String cContent) {
        this.cContent = cContent == null ? null : cContent.trim();
    }
}