package com.guo.technologyforum.dao.entity;

import java.util.Date;

public class Keep {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keep.n_id
     *
     * @mbg.generated
     */
    private Long nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keep.n_user_id
     *
     * @mbg.generated
     */
    private Long nUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keep.n_theme_id
     *
     * @mbg.generated
     */
    private Long nThemeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keep.d_keep_time
     *
     * @mbg.generated
     */
    private Date dKeepTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keep.n_type
     *
     * @mbg.generated
     */
    private Integer nType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keep.n_id
     *
     * @return the value of t_keep.n_id
     *
     * @mbg.generated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keep.n_id
     *
     * @param nId the value for t_keep.n_id
     *
     * @mbg.generated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keep.n_user_id
     *
     * @return the value of t_keep.n_user_id
     *
     * @mbg.generated
     */
    public Long getnUserId() {
        return nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keep.n_user_id
     *
     * @param nUserId the value for t_keep.n_user_id
     *
     * @mbg.generated
     */
    public void setnUserId(Long nUserId) {
        this.nUserId = nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keep.n_theme_id
     *
     * @return the value of t_keep.n_theme_id
     *
     * @mbg.generated
     */
    public Long getnThemeId() {
        return nThemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keep.n_theme_id
     *
     * @param nThemeId the value for t_keep.n_theme_id
     *
     * @mbg.generated
     */
    public void setnThemeId(Long nThemeId) {
        this.nThemeId = nThemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keep.d_keep_time
     *
     * @return the value of t_keep.d_keep_time
     *
     * @mbg.generated
     */
    public Date getdKeepTime() {
        return dKeepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keep.d_keep_time
     *
     * @param dKeepTime the value for t_keep.d_keep_time
     *
     * @mbg.generated
     */
    public void setdKeepTime(Date dKeepTime) {
        this.dKeepTime = dKeepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keep.n_type
     *
     * @return the value of t_keep.n_type
     *
     * @mbg.generated
     */
    public Integer getnType() {
        return nType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keep.n_type
     *
     * @param nType the value for t_keep.n_type
     *
     * @mbg.generated
     */
    public void setnType(Integer nType) {
        this.nType = nType;
    }
}