package com.guo.technologyforum.dao.entity;

public class KeepNodeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keep_node.n_user_id
     *
     * @mbg.generated
     */
    private Long nUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keep_node.n_node_id
     *
     * @mbg.generated
     */
    private Long nNodeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keep_node.n_user_id
     *
     * @return the value of t_keep_node.n_user_id
     *
     * @mbg.generated
     */
    public Long getnUserId() {
        return nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keep_node.n_user_id
     *
     * @param nUserId the value for t_keep_node.n_user_id
     *
     * @mbg.generated
     */
    public void setnUserId(Long nUserId) {
        this.nUserId = nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keep_node.n_node_id
     *
     * @return the value of t_keep_node.n_node_id
     *
     * @mbg.generated
     */
    public Long getnNodeId() {
        return nNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keep_node.n_node_id
     *
     * @param nNodeId the value for t_keep_node.n_node_id
     *
     * @mbg.generated
     */
    public void setnNodeId(Long nNodeId) {
        this.nNodeId = nNodeId;
    }
}