package com.guo.technologyforum.dao.entity;

public class KeepThemeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keep_theme.n_user_id
     *
     * @mbg.generated
     */
    private Long nUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keep_theme.n_theme_id
     *
     * @mbg.generated
     */
    private Long nThemeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keep_theme.n_user_id
     *
     * @return the value of t_keep_theme.n_user_id
     *
     * @mbg.generated
     */
    public Long getnUserId() {
        return nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keep_theme.n_user_id
     *
     * @param nUserId the value for t_keep_theme.n_user_id
     *
     * @mbg.generated
     */
    public void setnUserId(Long nUserId) {
        this.nUserId = nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keep_theme.n_theme_id
     *
     * @return the value of t_keep_theme.n_theme_id
     *
     * @mbg.generated
     */
    public Long getnThemeId() {
        return nThemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keep_theme.n_theme_id
     *
     * @param nThemeId the value for t_keep_theme.n_theme_id
     *
     * @mbg.generated
     */
    public void setnThemeId(Long nThemeId) {
        this.nThemeId = nThemeId;
    }
}