package com.guo.technologyforum.dao.entity;

import java.util.Date;

public class Right {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.n_id
     *
     * @mbg.generated
     */
    private Long nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.c_right_value
     *
     * @mbg.generated
     */
    private String cRightValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.d_create_time
     *
     * @mbg.generated
     */
    private Date dCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.n_pid
     *
     * @mbg.generated
     */
    private Long nPid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.n_id
     *
     * @return the value of t_right.n_id
     *
     * @mbg.generated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.n_id
     *
     * @param nId the value for t_right.n_id
     *
     * @mbg.generated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.c_right_value
     *
     * @return the value of t_right.c_right_value
     *
     * @mbg.generated
     */
    public String getcRightValue() {
        return cRightValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.c_right_value
     *
     * @param cRightValue the value for t_right.c_right_value
     *
     * @mbg.generated
     */
    public void setcRightValue(String cRightValue) {
        this.cRightValue = cRightValue == null ? null : cRightValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.c_name
     *
     * @return the value of t_right.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.c_name
     *
     * @param cName the value for t_right.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.d_create_time
     *
     * @return the value of t_right.d_create_time
     *
     * @mbg.generated
     */
    public Date getdCreateTime() {
        return dCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.d_create_time
     *
     * @param dCreateTime the value for t_right.d_create_time
     *
     * @mbg.generated
     */
    public void setdCreateTime(Date dCreateTime) {
        this.dCreateTime = dCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.n_pid
     *
     * @return the value of t_right.n_pid
     *
     * @mbg.generated
     */
    public Long getnPid() {
        return nPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.n_pid
     *
     * @param nPid the value for t_right.n_pid
     *
     * @mbg.generated
     */
    public void setnPid(Long nPid) {
        this.nPid = nPid;
    }
}