package com.guo.technologyforum.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    private static final long serialVersionUID = 5117282535856294812L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.n_id
     *
     * @mbg.generated
     */
    private Integer nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.d_create_time
     *
     * @mbg.generated
     */
    private Date dCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.n_id
     *
     * @return the value of t_role.n_id
     *
     * @mbg.generated
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.n_id
     *
     * @param nId the value for t_role.n_id
     *
     * @mbg.generated
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.c_name
     *
     * @return the value of t_role.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.c_name
     *
     * @param cName the value for t_role.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.d_create_time
     *
     * @return the value of t_role.d_create_time
     *
     * @mbg.generated
     */
    public Date getdCreateTime() {
        return dCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.d_create_time
     *
     * @param dCreateTime the value for t_role.d_create_time
     *
     * @mbg.generated
     */
    public void setdCreateTime(Date dCreateTime) {
        this.dCreateTime = dCreateTime;
    }
}