package com.guo.technologyforum.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Role_right implements Serializable {
    private static final long serialVersionUID = 3152927967388884174L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_right.n_id
     *
     * @mbg.generated
     */
    private Integer nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_right.n_role_id
     *
     * @mbg.generated
     */
    private Integer nRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_right.n_right_id
     *
     * @mbg.generated
     */
    private Integer nRightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_right.d_create_time
     *
     * @mbg.generated
     */
    private Date dCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_right.n_id
     *
     * @return the value of t_role_right.n_id
     *
     * @mbg.generated
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_right.n_id
     *
     * @param nId the value for t_role_right.n_id
     *
     * @mbg.generated
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_right.n_role_id
     *
     * @return the value of t_role_right.n_role_id
     *
     * @mbg.generated
     */
    public Integer getnRoleId() {
        return nRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_right.n_role_id
     *
     * @param nRoleId the value for t_role_right.n_role_id
     *
     * @mbg.generated
     */
    public void setnRoleId(Integer nRoleId) {
        this.nRoleId = nRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_right.n_right_id
     *
     * @return the value of t_role_right.n_right_id
     *
     * @mbg.generated
     */
    public Integer getnRightId() {
        return nRightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_right.n_right_id
     *
     * @param nRightId the value for t_role_right.n_right_id
     *
     * @mbg.generated
     */
    public void setnRightId(Integer nRightId) {
        this.nRightId = nRightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_right.d_create_time
     *
     * @return the value of t_role_right.d_create_time
     *
     * @mbg.generated
     */
    public Date getdCreateTime() {
        return dCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_right.d_create_time
     *
     * @param dCreateTime the value for t_role_right.d_create_time
     *
     * @mbg.generated
     */
    public void setdCreateTime(Date dCreateTime) {
        this.dCreateTime = dCreateTime;
    }
}