package com.guo.technologyforum.dao.entity;

import java.util.Date;

public class ThemeReply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.n_id
     *
     * @mbg.generated
     */
    private Long nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.n_theme_id
     *
     * @mbg.generated
     */
    private Long nThemeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.n_user_id
     *
     * @mbg.generated
     */
    private Long nUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.c_reply_content
     *
     * @mbg.generated
     */
    private String cReplyContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.n_like_count
     *
     * @mbg.generated
     */
    private Integer nLikeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.d_reply_time
     *
     * @mbg.generated
     */
    private Date dReplyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.d_lastupdate_time
     *
     * @mbg.generated
     */
    private Date dLastupdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.n_index
     *
     * @mbg.generated
     */
    private Integer nIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.n_reply_type
     *
     * @mbg.generated
     */
    private Integer nReplyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_theme_reply.n_reply_id
     *
     * @mbg.generated
     */
    private Long nReplyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.n_id
     *
     * @return the value of t_theme_reply.n_id
     *
     * @mbg.generated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.n_id
     *
     * @param nId the value for t_theme_reply.n_id
     *
     * @mbg.generated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.n_theme_id
     *
     * @return the value of t_theme_reply.n_theme_id
     *
     * @mbg.generated
     */
    public Long getnThemeId() {
        return nThemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.n_theme_id
     *
     * @param nThemeId the value for t_theme_reply.n_theme_id
     *
     * @mbg.generated
     */
    public void setnThemeId(Long nThemeId) {
        this.nThemeId = nThemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.n_user_id
     *
     * @return the value of t_theme_reply.n_user_id
     *
     * @mbg.generated
     */
    public Long getnUserId() {
        return nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.n_user_id
     *
     * @param nUserId the value for t_theme_reply.n_user_id
     *
     * @mbg.generated
     */
    public void setnUserId(Long nUserId) {
        this.nUserId = nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.c_reply_content
     *
     * @return the value of t_theme_reply.c_reply_content
     *
     * @mbg.generated
     */
    public String getcReplyContent() {
        return cReplyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.c_reply_content
     *
     * @param cReplyContent the value for t_theme_reply.c_reply_content
     *
     * @mbg.generated
     */
    public void setcReplyContent(String cReplyContent) {
        this.cReplyContent = cReplyContent == null ? null : cReplyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.n_like_count
     *
     * @return the value of t_theme_reply.n_like_count
     *
     * @mbg.generated
     */
    public Integer getnLikeCount() {
        return nLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.n_like_count
     *
     * @param nLikeCount the value for t_theme_reply.n_like_count
     *
     * @mbg.generated
     */
    public void setnLikeCount(Integer nLikeCount) {
        this.nLikeCount = nLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.d_reply_time
     *
     * @return the value of t_theme_reply.d_reply_time
     *
     * @mbg.generated
     */
    public Date getdReplyTime() {
        return dReplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.d_reply_time
     *
     * @param dReplyTime the value for t_theme_reply.d_reply_time
     *
     * @mbg.generated
     */
    public void setdReplyTime(Date dReplyTime) {
        this.dReplyTime = dReplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.d_lastupdate_time
     *
     * @return the value of t_theme_reply.d_lastupdate_time
     *
     * @mbg.generated
     */
    public Date getdLastupdateTime() {
        return dLastupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.d_lastupdate_time
     *
     * @param dLastupdateTime the value for t_theme_reply.d_lastupdate_time
     *
     * @mbg.generated
     */
    public void setdLastupdateTime(Date dLastupdateTime) {
        this.dLastupdateTime = dLastupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.n_index
     *
     * @return the value of t_theme_reply.n_index
     *
     * @mbg.generated
     */
    public Integer getnIndex() {
        return nIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.n_index
     *
     * @param nIndex the value for t_theme_reply.n_index
     *
     * @mbg.generated
     */
    public void setnIndex(Integer nIndex) {
        this.nIndex = nIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.n_reply_type
     *
     * @return the value of t_theme_reply.n_reply_type
     *
     * @mbg.generated
     */
    public Integer getnReplyType() {
        return nReplyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.n_reply_type
     *
     * @param nReplyType the value for t_theme_reply.n_reply_type
     *
     * @mbg.generated
     */
    public void setnReplyType(Integer nReplyType) {
        this.nReplyType = nReplyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_theme_reply.n_reply_id
     *
     * @return the value of t_theme_reply.n_reply_id
     *
     * @mbg.generated
     */
    public Long getnReplyId() {
        return nReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_theme_reply.n_reply_id
     *
     * @param nReplyId the value for t_theme_reply.n_reply_id
     *
     * @mbg.generated
     */
    public void setnReplyId(Long nReplyId) {
        this.nReplyId = nReplyId;
    }
}