package com.guo.technologyforum.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ThemeReplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public ThemeReplyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNIdIsNull() {
            addCriterion("n_id is null");
            return (Criteria) this;
        }

        public Criteria andNIdIsNotNull() {
            addCriterion("n_id is not null");
            return (Criteria) this;
        }

        public Criteria andNIdEqualTo(Long value) {
            addCriterion("n_id =", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdNotEqualTo(Long value) {
            addCriterion("n_id <>", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdGreaterThan(Long value) {
            addCriterion("n_id >", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdGreaterThanOrEqualTo(Long value) {
            addCriterion("n_id >=", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdLessThan(Long value) {
            addCriterion("n_id <", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdLessThanOrEqualTo(Long value) {
            addCriterion("n_id <=", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdIn(List<Long> values) {
            addCriterion("n_id in", values, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdNotIn(List<Long> values) {
            addCriterion("n_id not in", values, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdBetween(Long value1, Long value2) {
            addCriterion("n_id between", value1, value2, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdNotBetween(Long value1, Long value2) {
            addCriterion("n_id not between", value1, value2, "nId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdIsNull() {
            addCriterion("n_theme_id is null");
            return (Criteria) this;
        }

        public Criteria andNThemeIdIsNotNull() {
            addCriterion("n_theme_id is not null");
            return (Criteria) this;
        }

        public Criteria andNThemeIdEqualTo(Long value) {
            addCriterion("n_theme_id =", value, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdNotEqualTo(Long value) {
            addCriterion("n_theme_id <>", value, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdGreaterThan(Long value) {
            addCriterion("n_theme_id >", value, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("n_theme_id >=", value, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdLessThan(Long value) {
            addCriterion("n_theme_id <", value, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdLessThanOrEqualTo(Long value) {
            addCriterion("n_theme_id <=", value, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdIn(List<Long> values) {
            addCriterion("n_theme_id in", values, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdNotIn(List<Long> values) {
            addCriterion("n_theme_id not in", values, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdBetween(Long value1, Long value2) {
            addCriterion("n_theme_id between", value1, value2, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNThemeIdNotBetween(Long value1, Long value2) {
            addCriterion("n_theme_id not between", value1, value2, "nThemeId");
            return (Criteria) this;
        }

        public Criteria andNUserIdIsNull() {
            addCriterion("n_user_id is null");
            return (Criteria) this;
        }

        public Criteria andNUserIdIsNotNull() {
            addCriterion("n_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andNUserIdEqualTo(Long value) {
            addCriterion("n_user_id =", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdNotEqualTo(Long value) {
            addCriterion("n_user_id <>", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdGreaterThan(Long value) {
            addCriterion("n_user_id >", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("n_user_id >=", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdLessThan(Long value) {
            addCriterion("n_user_id <", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdLessThanOrEqualTo(Long value) {
            addCriterion("n_user_id <=", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdIn(List<Long> values) {
            addCriterion("n_user_id in", values, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdNotIn(List<Long> values) {
            addCriterion("n_user_id not in", values, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdBetween(Long value1, Long value2) {
            addCriterion("n_user_id between", value1, value2, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdNotBetween(Long value1, Long value2) {
            addCriterion("n_user_id not between", value1, value2, "nUserId");
            return (Criteria) this;
        }

        public Criteria andCReplyContentIsNull() {
            addCriterion("c_reply_content is null");
            return (Criteria) this;
        }

        public Criteria andCReplyContentIsNotNull() {
            addCriterion("c_reply_content is not null");
            return (Criteria) this;
        }

        public Criteria andCReplyContentEqualTo(String value) {
            addCriterion("c_reply_content =", value, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentNotEqualTo(String value) {
            addCriterion("c_reply_content <>", value, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentGreaterThan(String value) {
            addCriterion("c_reply_content >", value, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentGreaterThanOrEqualTo(String value) {
            addCriterion("c_reply_content >=", value, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentLessThan(String value) {
            addCriterion("c_reply_content <", value, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentLessThanOrEqualTo(String value) {
            addCriterion("c_reply_content <=", value, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentLike(String value) {
            addCriterion("c_reply_content like", value, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentNotLike(String value) {
            addCriterion("c_reply_content not like", value, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentIn(List<String> values) {
            addCriterion("c_reply_content in", values, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentNotIn(List<String> values) {
            addCriterion("c_reply_content not in", values, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentBetween(String value1, String value2) {
            addCriterion("c_reply_content between", value1, value2, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andCReplyContentNotBetween(String value1, String value2) {
            addCriterion("c_reply_content not between", value1, value2, "cReplyContent");
            return (Criteria) this;
        }

        public Criteria andNLikeCountIsNull() {
            addCriterion("n_like_count is null");
            return (Criteria) this;
        }

        public Criteria andNLikeCountIsNotNull() {
            addCriterion("n_like_count is not null");
            return (Criteria) this;
        }

        public Criteria andNLikeCountEqualTo(Integer value) {
            addCriterion("n_like_count =", value, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andNLikeCountNotEqualTo(Integer value) {
            addCriterion("n_like_count <>", value, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andNLikeCountGreaterThan(Integer value) {
            addCriterion("n_like_count >", value, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andNLikeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_like_count >=", value, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andNLikeCountLessThan(Integer value) {
            addCriterion("n_like_count <", value, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andNLikeCountLessThanOrEqualTo(Integer value) {
            addCriterion("n_like_count <=", value, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andNLikeCountIn(List<Integer> values) {
            addCriterion("n_like_count in", values, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andNLikeCountNotIn(List<Integer> values) {
            addCriterion("n_like_count not in", values, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andNLikeCountBetween(Integer value1, Integer value2) {
            addCriterion("n_like_count between", value1, value2, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andNLikeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("n_like_count not between", value1, value2, "nLikeCount");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeIsNull() {
            addCriterion("d_reply_time is null");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeIsNotNull() {
            addCriterion("d_reply_time is not null");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeEqualTo(Date value) {
            addCriterion("d_reply_time =", value, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeNotEqualTo(Date value) {
            addCriterion("d_reply_time <>", value, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeGreaterThan(Date value) {
            addCriterion("d_reply_time >", value, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("d_reply_time >=", value, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeLessThan(Date value) {
            addCriterion("d_reply_time <", value, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeLessThanOrEqualTo(Date value) {
            addCriterion("d_reply_time <=", value, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeIn(List<Date> values) {
            addCriterion("d_reply_time in", values, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeNotIn(List<Date> values) {
            addCriterion("d_reply_time not in", values, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeBetween(Date value1, Date value2) {
            addCriterion("d_reply_time between", value1, value2, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDReplyTimeNotBetween(Date value1, Date value2) {
            addCriterion("d_reply_time not between", value1, value2, "dReplyTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeIsNull() {
            addCriterion("d_lastupdate_time is null");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeIsNotNull() {
            addCriterion("d_lastupdate_time is not null");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeEqualTo(Date value) {
            addCriterion("d_lastupdate_time =", value, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeNotEqualTo(Date value) {
            addCriterion("d_lastupdate_time <>", value, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeGreaterThan(Date value) {
            addCriterion("d_lastupdate_time >", value, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("d_lastupdate_time >=", value, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeLessThan(Date value) {
            addCriterion("d_lastupdate_time <", value, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("d_lastupdate_time <=", value, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeIn(List<Date> values) {
            addCriterion("d_lastupdate_time in", values, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeNotIn(List<Date> values) {
            addCriterion("d_lastupdate_time not in", values, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeBetween(Date value1, Date value2) {
            addCriterion("d_lastupdate_time between", value1, value2, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andDLastupdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("d_lastupdate_time not between", value1, value2, "dLastupdateTime");
            return (Criteria) this;
        }

        public Criteria andNIndexIsNull() {
            addCriterion("n_index is null");
            return (Criteria) this;
        }

        public Criteria andNIndexIsNotNull() {
            addCriterion("n_index is not null");
            return (Criteria) this;
        }

        public Criteria andNIndexEqualTo(Integer value) {
            addCriterion("n_index =", value, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNIndexNotEqualTo(Integer value) {
            addCriterion("n_index <>", value, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNIndexGreaterThan(Integer value) {
            addCriterion("n_index >", value, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_index >=", value, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNIndexLessThan(Integer value) {
            addCriterion("n_index <", value, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNIndexLessThanOrEqualTo(Integer value) {
            addCriterion("n_index <=", value, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNIndexIn(List<Integer> values) {
            addCriterion("n_index in", values, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNIndexNotIn(List<Integer> values) {
            addCriterion("n_index not in", values, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNIndexBetween(Integer value1, Integer value2) {
            addCriterion("n_index between", value1, value2, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("n_index not between", value1, value2, "nIndex");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeIsNull() {
            addCriterion("n_reply_type is null");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeIsNotNull() {
            addCriterion("n_reply_type is not null");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeEqualTo(Integer value) {
            addCriterion("n_reply_type =", value, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeNotEqualTo(Integer value) {
            addCriterion("n_reply_type <>", value, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeGreaterThan(Integer value) {
            addCriterion("n_reply_type >", value, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_reply_type >=", value, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeLessThan(Integer value) {
            addCriterion("n_reply_type <", value, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeLessThanOrEqualTo(Integer value) {
            addCriterion("n_reply_type <=", value, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeIn(List<Integer> values) {
            addCriterion("n_reply_type in", values, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeNotIn(List<Integer> values) {
            addCriterion("n_reply_type not in", values, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeBetween(Integer value1, Integer value2) {
            addCriterion("n_reply_type between", value1, value2, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("n_reply_type not between", value1, value2, "nReplyType");
            return (Criteria) this;
        }

        public Criteria andNReplyIdIsNull() {
            addCriterion("n_reply_id is null");
            return (Criteria) this;
        }

        public Criteria andNReplyIdIsNotNull() {
            addCriterion("n_reply_id is not null");
            return (Criteria) this;
        }

        public Criteria andNReplyIdEqualTo(Long value) {
            addCriterion("n_reply_id =", value, "nReplyId");
            return (Criteria) this;
        }

        public Criteria andNReplyIdNotEqualTo(Long value) {
            addCriterion("n_reply_id <>", value, "nReplyId");
            return (Criteria) this;
        }

        public Criteria andNReplyIdGreaterThan(Long value) {
            addCriterion("n_reply_id >", value, "nReplyId");
            return (Criteria) this;
        }

        public Criteria andNReplyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("n_reply_id >=", value, "nReplyId");
            return (Criteria) this;
        }

        public Criteria andNReplyIdLessThan(Long value) {
            addCriterion("n_reply_id <", value, "nReplyId");
            return (Criteria) this;
        }

        public Criteria andNReplyIdLessThanOrEqualTo(Long value) {
            addCriterion("n_reply_id <=", value, "nReplyId");
            return (Criteria) this;
        }

        public Criteria andNReplyIdIn(List<Long> values) {
            addCriterion("n_reply_id in", values, "nReplyId");
            return (Criteria) this;
        }

        public Criteria andNReplyIdNotIn(List<Long> values) {
            addCriterion("n_reply_id not in", values, "nReplyId");
            return (Criteria) this;
        }

        public Criteria andNReplyIdBetween(Long value1, Long value2) {
            addCriterion("n_reply_id between", value1, value2, "nReplyId");
            return (Criteria) this;
        }

        public Criteria andNReplyIdNotBetween(Long value1, Long value2) {
            addCriterion("n_reply_id not between", value1, value2, "nReplyId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_theme_reply
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_theme_reply
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}