package com.guo.technologyforum.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ThemeClassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public ThemeClassExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNIdIsNull() {
            addCriterion("n_id is null");
            return (Criteria) this;
        }

        public Criteria andNIdIsNotNull() {
            addCriterion("n_id is not null");
            return (Criteria) this;
        }

        public Criteria andNIdEqualTo(Integer value) {
            addCriterion("n_id =", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdNotEqualTo(Integer value) {
            addCriterion("n_id <>", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdGreaterThan(Integer value) {
            addCriterion("n_id >", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_id >=", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdLessThan(Integer value) {
            addCriterion("n_id <", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdLessThanOrEqualTo(Integer value) {
            addCriterion("n_id <=", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdIn(List<Integer> values) {
            addCriterion("n_id in", values, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdNotIn(List<Integer> values) {
            addCriterion("n_id not in", values, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdBetween(Integer value1, Integer value2) {
            addCriterion("n_id between", value1, value2, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdNotBetween(Integer value1, Integer value2) {
            addCriterion("n_id not between", value1, value2, "nId");
            return (Criteria) this;
        }

        public Criteria andNParentidIsNull() {
            addCriterion("n_parentid is null");
            return (Criteria) this;
        }

        public Criteria andNParentidIsNotNull() {
            addCriterion("n_parentid is not null");
            return (Criteria) this;
        }

        public Criteria andNParentidEqualTo(Integer value) {
            addCriterion("n_parentid =", value, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNParentidNotEqualTo(Integer value) {
            addCriterion("n_parentid <>", value, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNParentidGreaterThan(Integer value) {
            addCriterion("n_parentid >", value, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNParentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_parentid >=", value, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNParentidLessThan(Integer value) {
            addCriterion("n_parentid <", value, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNParentidLessThanOrEqualTo(Integer value) {
            addCriterion("n_parentid <=", value, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNParentidIn(List<Integer> values) {
            addCriterion("n_parentid in", values, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNParentidNotIn(List<Integer> values) {
            addCriterion("n_parentid not in", values, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNParentidBetween(Integer value1, Integer value2) {
            addCriterion("n_parentid between", value1, value2, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNParentidNotBetween(Integer value1, Integer value2) {
            addCriterion("n_parentid not between", value1, value2, "nParentid");
            return (Criteria) this;
        }

        public Criteria andNDepthIsNull() {
            addCriterion("n_depth is null");
            return (Criteria) this;
        }

        public Criteria andNDepthIsNotNull() {
            addCriterion("n_depth is not null");
            return (Criteria) this;
        }

        public Criteria andNDepthEqualTo(String value) {
            addCriterion("n_depth =", value, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthNotEqualTo(String value) {
            addCriterion("n_depth <>", value, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthGreaterThan(String value) {
            addCriterion("n_depth >", value, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthGreaterThanOrEqualTo(String value) {
            addCriterion("n_depth >=", value, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthLessThan(String value) {
            addCriterion("n_depth <", value, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthLessThanOrEqualTo(String value) {
            addCriterion("n_depth <=", value, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthLike(String value) {
            addCriterion("n_depth like", value, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthNotLike(String value) {
            addCriterion("n_depth not like", value, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthIn(List<String> values) {
            addCriterion("n_depth in", values, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthNotIn(List<String> values) {
            addCriterion("n_depth not in", values, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthBetween(String value1, String value2) {
            addCriterion("n_depth between", value1, value2, "nDepth");
            return (Criteria) this;
        }

        public Criteria andNDepthNotBetween(String value1, String value2) {
            addCriterion("n_depth not between", value1, value2, "nDepth");
            return (Criteria) this;
        }

        public Criteria andCNameIsNull() {
            addCriterion("c_name is null");
            return (Criteria) this;
        }

        public Criteria andCNameIsNotNull() {
            addCriterion("c_name is not null");
            return (Criteria) this;
        }

        public Criteria andCNameEqualTo(String value) {
            addCriterion("c_name =", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotEqualTo(String value) {
            addCriterion("c_name <>", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThan(String value) {
            addCriterion("c_name >", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThanOrEqualTo(String value) {
            addCriterion("c_name >=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThan(String value) {
            addCriterion("c_name <", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThanOrEqualTo(String value) {
            addCriterion("c_name <=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLike(String value) {
            addCriterion("c_name like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotLike(String value) {
            addCriterion("c_name not like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameIn(List<String> values) {
            addCriterion("c_name in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotIn(List<String> values) {
            addCriterion("c_name not in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameBetween(String value1, String value2) {
            addCriterion("c_name between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotBetween(String value1, String value2) {
            addCriterion("c_name not between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andNOrderIsNull() {
            addCriterion("n_order is null");
            return (Criteria) this;
        }

        public Criteria andNOrderIsNotNull() {
            addCriterion("n_order is not null");
            return (Criteria) this;
        }

        public Criteria andNOrderEqualTo(Integer value) {
            addCriterion("n_order =", value, "nOrder");
            return (Criteria) this;
        }

        public Criteria andNOrderNotEqualTo(Integer value) {
            addCriterion("n_order <>", value, "nOrder");
            return (Criteria) this;
        }

        public Criteria andNOrderGreaterThan(Integer value) {
            addCriterion("n_order >", value, "nOrder");
            return (Criteria) this;
        }

        public Criteria andNOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_order >=", value, "nOrder");
            return (Criteria) this;
        }

        public Criteria andNOrderLessThan(Integer value) {
            addCriterion("n_order <", value, "nOrder");
            return (Criteria) this;
        }

        public Criteria andNOrderLessThanOrEqualTo(Integer value) {
            addCriterion("n_order <=", value, "nOrder");
            return (Criteria) this;
        }

        public Criteria andNOrderIn(List<Integer> values) {
            addCriterion("n_order in", values, "nOrder");
            return (Criteria) this;
        }

        public Criteria andNOrderNotIn(List<Integer> values) {
            addCriterion("n_order not in", values, "nOrder");
            return (Criteria) this;
        }

        public Criteria andNOrderBetween(Integer value1, Integer value2) {
            addCriterion("n_order between", value1, value2, "nOrder");
            return (Criteria) this;
        }

        public Criteria andNOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("n_order not between", value1, value2, "nOrder");
            return (Criteria) this;
        }

        public Criteria andBEnableIsNull() {
            addCriterion("b_enable is null");
            return (Criteria) this;
        }

        public Criteria andBEnableIsNotNull() {
            addCriterion("b_enable is not null");
            return (Criteria) this;
        }

        public Criteria andBEnableEqualTo(Boolean value) {
            addCriterion("b_enable =", value, "bEnable");
            return (Criteria) this;
        }

        public Criteria andBEnableNotEqualTo(Boolean value) {
            addCriterion("b_enable <>", value, "bEnable");
            return (Criteria) this;
        }

        public Criteria andBEnableGreaterThan(Boolean value) {
            addCriterion("b_enable >", value, "bEnable");
            return (Criteria) this;
        }

        public Criteria andBEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("b_enable >=", value, "bEnable");
            return (Criteria) this;
        }

        public Criteria andBEnableLessThan(Boolean value) {
            addCriterion("b_enable <", value, "bEnable");
            return (Criteria) this;
        }

        public Criteria andBEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("b_enable <=", value, "bEnable");
            return (Criteria) this;
        }

        public Criteria andBEnableIn(List<Boolean> values) {
            addCriterion("b_enable in", values, "bEnable");
            return (Criteria) this;
        }

        public Criteria andBEnableNotIn(List<Boolean> values) {
            addCriterion("b_enable not in", values, "bEnable");
            return (Criteria) this;
        }

        public Criteria andBEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("b_enable between", value1, value2, "bEnable");
            return (Criteria) this;
        }

        public Criteria andBEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("b_enable not between", value1, value2, "bEnable");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeIsNull() {
            addCriterion("d_createtime is null");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeIsNotNull() {
            addCriterion("d_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeEqualTo(Date value) {
            addCriterion("d_createtime =", value, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeNotEqualTo(Date value) {
            addCriterion("d_createtime <>", value, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeGreaterThan(Date value) {
            addCriterion("d_createtime >", value, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("d_createtime >=", value, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeLessThan(Date value) {
            addCriterion("d_createtime <", value, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("d_createtime <=", value, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeIn(List<Date> values) {
            addCriterion("d_createtime in", values, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeNotIn(List<Date> values) {
            addCriterion("d_createtime not in", values, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeBetween(Date value1, Date value2) {
            addCriterion("d_createtime between", value1, value2, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andDCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("d_createtime not between", value1, value2, "dCreatetime");
            return (Criteria) this;
        }

        public Criteria andCDescriptionIsNull() {
            addCriterion("c_description is null");
            return (Criteria) this;
        }

        public Criteria andCDescriptionIsNotNull() {
            addCriterion("c_description is not null");
            return (Criteria) this;
        }

        public Criteria andCDescriptionEqualTo(String value) {
            addCriterion("c_description =", value, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionNotEqualTo(String value) {
            addCriterion("c_description <>", value, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionGreaterThan(String value) {
            addCriterion("c_description >", value, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("c_description >=", value, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionLessThan(String value) {
            addCriterion("c_description <", value, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionLessThanOrEqualTo(String value) {
            addCriterion("c_description <=", value, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionLike(String value) {
            addCriterion("c_description like", value, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionNotLike(String value) {
            addCriterion("c_description not like", value, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionIn(List<String> values) {
            addCriterion("c_description in", values, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionNotIn(List<String> values) {
            addCriterion("c_description not in", values, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionBetween(String value1, String value2) {
            addCriterion("c_description between", value1, value2, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCDescriptionNotBetween(String value1, String value2) {
            addCriterion("c_description not between", value1, value2, "cDescription");
            return (Criteria) this;
        }

        public Criteria andCImgUrlIsNull() {
            addCriterion("c_img_url is null");
            return (Criteria) this;
        }

        public Criteria andCImgUrlIsNotNull() {
            addCriterion("c_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andCImgUrlEqualTo(String value) {
            addCriterion("c_img_url =", value, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlNotEqualTo(String value) {
            addCriterion("c_img_url <>", value, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlGreaterThan(String value) {
            addCriterion("c_img_url >", value, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("c_img_url >=", value, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlLessThan(String value) {
            addCriterion("c_img_url <", value, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlLessThanOrEqualTo(String value) {
            addCriterion("c_img_url <=", value, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlLike(String value) {
            addCriterion("c_img_url like", value, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlNotLike(String value) {
            addCriterion("c_img_url not like", value, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlIn(List<String> values) {
            addCriterion("c_img_url in", values, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlNotIn(List<String> values) {
            addCriterion("c_img_url not in", values, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlBetween(String value1, String value2) {
            addCriterion("c_img_url between", value1, value2, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCImgUrlNotBetween(String value1, String value2) {
            addCriterion("c_img_url not between", value1, value2, "cImgUrl");
            return (Criteria) this;
        }

        public Criteria andCRouterIsNull() {
            addCriterion("c_router is null");
            return (Criteria) this;
        }

        public Criteria andCRouterIsNotNull() {
            addCriterion("c_router is not null");
            return (Criteria) this;
        }

        public Criteria andCRouterEqualTo(String value) {
            addCriterion("c_router =", value, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterNotEqualTo(String value) {
            addCriterion("c_router <>", value, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterGreaterThan(String value) {
            addCriterion("c_router >", value, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterGreaterThanOrEqualTo(String value) {
            addCriterion("c_router >=", value, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterLessThan(String value) {
            addCriterion("c_router <", value, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterLessThanOrEqualTo(String value) {
            addCriterion("c_router <=", value, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterLike(String value) {
            addCriterion("c_router like", value, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterNotLike(String value) {
            addCriterion("c_router not like", value, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterIn(List<String> values) {
            addCriterion("c_router in", values, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterNotIn(List<String> values) {
            addCriterion("c_router not in", values, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterBetween(String value1, String value2) {
            addCriterion("c_router between", value1, value2, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCRouterNotBetween(String value1, String value2) {
            addCriterion("c_router not between", value1, value2, "cRouter");
            return (Criteria) this;
        }

        public Criteria andCTypeIsNull() {
            addCriterion("c_type is null");
            return (Criteria) this;
        }

        public Criteria andCTypeIsNotNull() {
            addCriterion("c_type is not null");
            return (Criteria) this;
        }

        public Criteria andCTypeEqualTo(String value) {
            addCriterion("c_type =", value, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeNotEqualTo(String value) {
            addCriterion("c_type <>", value, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeGreaterThan(String value) {
            addCriterion("c_type >", value, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeGreaterThanOrEqualTo(String value) {
            addCriterion("c_type >=", value, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeLessThan(String value) {
            addCriterion("c_type <", value, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeLessThanOrEqualTo(String value) {
            addCriterion("c_type <=", value, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeLike(String value) {
            addCriterion("c_type like", value, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeNotLike(String value) {
            addCriterion("c_type not like", value, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeIn(List<String> values) {
            addCriterion("c_type in", values, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeNotIn(List<String> values) {
            addCriterion("c_type not in", values, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeBetween(String value1, String value2) {
            addCriterion("c_type between", value1, value2, "cType");
            return (Criteria) this;
        }

        public Criteria andCTypeNotBetween(String value1, String value2) {
            addCriterion("c_type not between", value1, value2, "cType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_theme_class
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_theme_class
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}