package com.guo.technologyforum.dao.entity;

public class UserAttentionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_attention.n_user_id
     *
     * @mbg.generated
     */
    private Long nUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_attention.n_attention_user_id
     *
     * @mbg.generated
     */
    private String nAttentionUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_attention.n_user_id
     *
     * @return the value of t_user_attention.n_user_id
     *
     * @mbg.generated
     */
    public Long getnUserId() {
        return nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_attention.n_user_id
     *
     * @param nUserId the value for t_user_attention.n_user_id
     *
     * @mbg.generated
     */
    public void setnUserId(Long nUserId) {
        this.nUserId = nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_attention.n_attention_user_id
     *
     * @return the value of t_user_attention.n_attention_user_id
     *
     * @mbg.generated
     */
    public String getnAttentionUserId() {
        return nAttentionUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_attention.n_attention_user_id
     *
     * @param nAttentionUserId the value for t_user_attention.n_attention_user_id
     *
     * @mbg.generated
     */
    public void setnAttentionUserId(String nAttentionUserId) {
        this.nAttentionUserId = nAttentionUserId == null ? null : nAttentionUserId.trim();
    }
}