package com.guo.technologyforum.dao.entity;

import java.util.Date;
import java.util.UUID;

public class UserAttention extends UserAttentionKey {
    public UserAttention(){
        this.cId = UUID.randomUUID().toString().replace("-", "");
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_attention.c_id
     *
     * @mbg.generated
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_attention.d_attention_time
     *
     * @mbg.generated
     */
    private Date dAttentionTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_attention.c_id
     *
     * @return the value of t_user_attention.c_id
     *
     * @mbg.generated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_attention.c_id
     *
     * @param cId the value for t_user_attention.c_id
     *
     * @mbg.generated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_attention.d_attention_time
     *
     * @return the value of t_user_attention.d_attention_time
     *
     * @mbg.generated
     */
    public Date getdAttentionTime() {
        return dAttentionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_attention.d_attention_time
     *
     * @param dAttentionTime the value for t_user_attention.d_attention_time
     *
     * @mbg.generated
     */
    public void setdAttentionTime(Date dAttentionTime) {
        this.dAttentionTime = dAttentionTime;
    }
}