package com.guo.technologyforum.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserAttentionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public UserAttentionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNUserIdIsNull() {
            addCriterion("n_user_id is null");
            return (Criteria) this;
        }

        public Criteria andNUserIdIsNotNull() {
            addCriterion("n_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andNUserIdEqualTo(Long value) {
            addCriterion("n_user_id =", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdNotEqualTo(Long value) {
            addCriterion("n_user_id <>", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdGreaterThan(Long value) {
            addCriterion("n_user_id >", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("n_user_id >=", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdLessThan(Long value) {
            addCriterion("n_user_id <", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdLessThanOrEqualTo(Long value) {
            addCriterion("n_user_id <=", value, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdIn(List<Long> values) {
            addCriterion("n_user_id in", values, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdNotIn(List<Long> values) {
            addCriterion("n_user_id not in", values, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdBetween(Long value1, Long value2) {
            addCriterion("n_user_id between", value1, value2, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNUserIdNotBetween(Long value1, Long value2) {
            addCriterion("n_user_id not between", value1, value2, "nUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdIsNull() {
            addCriterion("n_attention_user_id is null");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdIsNotNull() {
            addCriterion("n_attention_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdEqualTo(Long value) {
            addCriterion("n_attention_user_id =", value, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdNotEqualTo(Long value) {
            addCriterion("n_attention_user_id <>", value, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdGreaterThan(Long value) {
            addCriterion("n_attention_user_id >", value, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("n_attention_user_id >=", value, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdLessThan(Long value) {
            addCriterion("n_attention_user_id <", value, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdLessThanOrEqualTo(Long value) {
            addCriterion("n_attention_user_id <=", value, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdIn(List<Long> values) {
            addCriterion("n_attention_user_id in", values, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdNotIn(List<Long> values) {
            addCriterion("n_attention_user_id not in", values, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdBetween(Long value1, Long value2) {
            addCriterion("n_attention_user_id between", value1, value2, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andNAttentionUserIdNotBetween(Long value1, Long value2) {
            addCriterion("n_attention_user_id not between", value1, value2, "nAttentionUserId");
            return (Criteria) this;
        }

        public Criteria andCIdIsNull() {
            addCriterion("c_id is null");
            return (Criteria) this;
        }

        public Criteria andCIdIsNotNull() {
            addCriterion("c_id is not null");
            return (Criteria) this;
        }

        public Criteria andCIdEqualTo(String value) {
            addCriterion("c_id =", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotEqualTo(String value) {
            addCriterion("c_id <>", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThan(String value) {
            addCriterion("c_id >", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThanOrEqualTo(String value) {
            addCriterion("c_id >=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThan(String value) {
            addCriterion("c_id <", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThanOrEqualTo(String value) {
            addCriterion("c_id <=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLike(String value) {
            addCriterion("c_id like", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotLike(String value) {
            addCriterion("c_id not like", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdIn(List<String> values) {
            addCriterion("c_id in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotIn(List<String> values) {
            addCriterion("c_id not in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdBetween(String value1, String value2) {
            addCriterion("c_id between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotBetween(String value1, String value2) {
            addCriterion("c_id not between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeIsNull() {
            addCriterion("d_attention_time is null");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeIsNotNull() {
            addCriterion("d_attention_time is not null");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeEqualTo(Date value) {
            addCriterion("d_attention_time =", value, "dAttentionTime");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeNotEqualTo(Date value) {
            addCriterion("d_attention_time <>", value, "dAttentionTime");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeGreaterThan(Date value) {
            addCriterion("d_attention_time >", value, "dAttentionTime");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("d_attention_time >=", value, "dAttentionTime");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeLessThan(Date value) {
            addCriterion("d_attention_time <", value, "dAttentionTime");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeLessThanOrEqualTo(Date value) {
            addCriterion("d_attention_time <=", value, "dAttentionTime");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeIn(List<Date> values) {
            addCriterion("d_attention_time in", values, "dAttentionTime");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeNotIn(List<Date> values) {
            addCriterion("d_attention_time not in", values, "dAttentionTime");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeBetween(Date value1, Date value2) {
            addCriterion("d_attention_time between", value1, value2, "dAttentionTime");
            return (Criteria) this;
        }

        public Criteria andDAttentionTimeNotBetween(Date value1, Date value2) {
            addCriterion("d_attention_time not between", value1, value2, "dAttentionTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_attention
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_attention
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}