package com.guo.technologyforum.dao.entity;

public class UserBlockKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_block.n_user_id
     *
     * @mbg.generated
     */
    private Long nUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_block.n_block_user_id
     *
     * @mbg.generated
     */
    private String nBlockUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_block.n_user_id
     *
     * @return the value of t_user_block.n_user_id
     *
     * @mbg.generated
     */
    public Long getnUserId() {
        return nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_block.n_user_id
     *
     * @param nUserId the value for t_user_block.n_user_id
     *
     * @mbg.generated
     */
    public void setnUserId(Long nUserId) {
        this.nUserId = nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_block.n_block_user_id
     *
     * @return the value of t_user_block.n_block_user_id
     *
     * @mbg.generated
     */
    public String getnBlockUserId() {
        return nBlockUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_block.n_block_user_id
     *
     * @param nBlockUserId the value for t_user_block.n_block_user_id
     *
     * @mbg.generated
     */
    public void setnBlockUserId(String nBlockUserId) {
        this.nBlockUserId = nBlockUserId == null ? null : nBlockUserId.trim();
    }
}