package com.guo.technologyforum.dao.entity;

import java.util.Date;
import java.util.UUID;

public class UserBlock extends UserBlockKey {
    public UserBlock(){
        this.cId = UUID.randomUUID().toString().replace("-", "");
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_block.c_id
     *
     * @mbg.generated
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_block.d_block_time
     *
     * @mbg.generated
     */
    private Date dBlockTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_block.c_id
     *
     * @return the value of t_user_block.c_id
     *
     * @mbg.generated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_block.c_id
     *
     * @param cId the value for t_user_block.c_id
     *
     * @mbg.generated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_block.d_block_time
     *
     * @return the value of t_user_block.d_block_time
     *
     * @mbg.generated
     */
    public Date getdBlockTime() {
        return dBlockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_block.d_block_time
     *
     * @param dBlockTime the value for t_user_block.d_block_time
     *
     * @mbg.generated
     */
    public void setdBlockTime(Date dBlockTime) {
        this.dBlockTime = dBlockTime;
    }
}