package com.guo.technologyforum.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public UserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNIdIsNull() {
            addCriterion("n_id is null");
            return (Criteria) this;
        }

        public Criteria andNIdIsNotNull() {
            addCriterion("n_id is not null");
            return (Criteria) this;
        }

        public Criteria andNIdEqualTo(Long value) {
            addCriterion("n_id =", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdNotEqualTo(Long value) {
            addCriterion("n_id <>", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdGreaterThan(Long value) {
            addCriterion("n_id >", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdGreaterThanOrEqualTo(Long value) {
            addCriterion("n_id >=", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdLessThan(Long value) {
            addCriterion("n_id <", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdLessThanOrEqualTo(Long value) {
            addCriterion("n_id <=", value, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdIn(List<Long> values) {
            addCriterion("n_id in", values, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdNotIn(List<Long> values) {
            addCriterion("n_id not in", values, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdBetween(Long value1, Long value2) {
            addCriterion("n_id between", value1, value2, "nId");
            return (Criteria) this;
        }

        public Criteria andNIdNotBetween(Long value1, Long value2) {
            addCriterion("n_id not between", value1, value2, "nId");
            return (Criteria) this;
        }

        public Criteria andCUsernameIsNull() {
            addCriterion("c_username is null");
            return (Criteria) this;
        }

        public Criteria andCUsernameIsNotNull() {
            addCriterion("c_username is not null");
            return (Criteria) this;
        }

        public Criteria andCUsernameEqualTo(String value) {
            addCriterion("c_username =", value, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameNotEqualTo(String value) {
            addCriterion("c_username <>", value, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameGreaterThan(String value) {
            addCriterion("c_username >", value, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("c_username >=", value, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameLessThan(String value) {
            addCriterion("c_username <", value, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameLessThanOrEqualTo(String value) {
            addCriterion("c_username <=", value, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameLike(String value) {
            addCriterion("c_username like", value, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameNotLike(String value) {
            addCriterion("c_username not like", value, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameIn(List<String> values) {
            addCriterion("c_username in", values, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameNotIn(List<String> values) {
            addCriterion("c_username not in", values, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameBetween(String value1, String value2) {
            addCriterion("c_username between", value1, value2, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCUsernameNotBetween(String value1, String value2) {
            addCriterion("c_username not between", value1, value2, "cUsername");
            return (Criteria) this;
        }

        public Criteria andCPasswordIsNull() {
            addCriterion("c_password is null");
            return (Criteria) this;
        }

        public Criteria andCPasswordIsNotNull() {
            addCriterion("c_password is not null");
            return (Criteria) this;
        }

        public Criteria andCPasswordEqualTo(String value) {
            addCriterion("c_password =", value, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordNotEqualTo(String value) {
            addCriterion("c_password <>", value, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordGreaterThan(String value) {
            addCriterion("c_password >", value, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("c_password >=", value, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordLessThan(String value) {
            addCriterion("c_password <", value, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordLessThanOrEqualTo(String value) {
            addCriterion("c_password <=", value, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordLike(String value) {
            addCriterion("c_password like", value, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordNotLike(String value) {
            addCriterion("c_password not like", value, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordIn(List<String> values) {
            addCriterion("c_password in", values, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordNotIn(List<String> values) {
            addCriterion("c_password not in", values, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordBetween(String value1, String value2) {
            addCriterion("c_password between", value1, value2, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCPasswordNotBetween(String value1, String value2) {
            addCriterion("c_password not between", value1, value2, "cPassword");
            return (Criteria) this;
        }

        public Criteria andCSaltIsNull() {
            addCriterion("c_salt is null");
            return (Criteria) this;
        }

        public Criteria andCSaltIsNotNull() {
            addCriterion("c_salt is not null");
            return (Criteria) this;
        }

        public Criteria andCSaltEqualTo(String value) {
            addCriterion("c_salt =", value, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltNotEqualTo(String value) {
            addCriterion("c_salt <>", value, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltGreaterThan(String value) {
            addCriterion("c_salt >", value, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltGreaterThanOrEqualTo(String value) {
            addCriterion("c_salt >=", value, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltLessThan(String value) {
            addCriterion("c_salt <", value, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltLessThanOrEqualTo(String value) {
            addCriterion("c_salt <=", value, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltLike(String value) {
            addCriterion("c_salt like", value, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltNotLike(String value) {
            addCriterion("c_salt not like", value, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltIn(List<String> values) {
            addCriterion("c_salt in", values, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltNotIn(List<String> values) {
            addCriterion("c_salt not in", values, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltBetween(String value1, String value2) {
            addCriterion("c_salt between", value1, value2, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCSaltNotBetween(String value1, String value2) {
            addCriterion("c_salt not between", value1, value2, "cSalt");
            return (Criteria) this;
        }

        public Criteria andCEmailIsNull() {
            addCriterion("c_email is null");
            return (Criteria) this;
        }

        public Criteria andCEmailIsNotNull() {
            addCriterion("c_email is not null");
            return (Criteria) this;
        }

        public Criteria andCEmailEqualTo(String value) {
            addCriterion("c_email =", value, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailNotEqualTo(String value) {
            addCriterion("c_email <>", value, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailGreaterThan(String value) {
            addCriterion("c_email >", value, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailGreaterThanOrEqualTo(String value) {
            addCriterion("c_email >=", value, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailLessThan(String value) {
            addCriterion("c_email <", value, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailLessThanOrEqualTo(String value) {
            addCriterion("c_email <=", value, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailLike(String value) {
            addCriterion("c_email like", value, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailNotLike(String value) {
            addCriterion("c_email not like", value, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailIn(List<String> values) {
            addCriterion("c_email in", values, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailNotIn(List<String> values) {
            addCriterion("c_email not in", values, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailBetween(String value1, String value2) {
            addCriterion("c_email between", value1, value2, "cEmail");
            return (Criteria) this;
        }

        public Criteria andCEmailNotBetween(String value1, String value2) {
            addCriterion("c_email not between", value1, value2, "cEmail");
            return (Criteria) this;
        }

        public Criteria andNSexIsNull() {
            addCriterion("n_sex is null");
            return (Criteria) this;
        }

        public Criteria andNSexIsNotNull() {
            addCriterion("n_sex is not null");
            return (Criteria) this;
        }

        public Criteria andNSexEqualTo(Integer value) {
            addCriterion("n_sex =", value, "nSex");
            return (Criteria) this;
        }

        public Criteria andNSexNotEqualTo(Integer value) {
            addCriterion("n_sex <>", value, "nSex");
            return (Criteria) this;
        }

        public Criteria andNSexGreaterThan(Integer value) {
            addCriterion("n_sex >", value, "nSex");
            return (Criteria) this;
        }

        public Criteria andNSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_sex >=", value, "nSex");
            return (Criteria) this;
        }

        public Criteria andNSexLessThan(Integer value) {
            addCriterion("n_sex <", value, "nSex");
            return (Criteria) this;
        }

        public Criteria andNSexLessThanOrEqualTo(Integer value) {
            addCriterion("n_sex <=", value, "nSex");
            return (Criteria) this;
        }

        public Criteria andNSexIn(List<Integer> values) {
            addCriterion("n_sex in", values, "nSex");
            return (Criteria) this;
        }

        public Criteria andNSexNotIn(List<Integer> values) {
            addCriterion("n_sex not in", values, "nSex");
            return (Criteria) this;
        }

        public Criteria andNSexBetween(Integer value1, Integer value2) {
            addCriterion("n_sex between", value1, value2, "nSex");
            return (Criteria) this;
        }

        public Criteria andNSexNotBetween(Integer value1, Integer value2) {
            addCriterion("n_sex not between", value1, value2, "nSex");
            return (Criteria) this;
        }

        public Criteria andCTelephoneIsNull() {
            addCriterion("c_telephone is null");
            return (Criteria) this;
        }

        public Criteria andCTelephoneIsNotNull() {
            addCriterion("c_telephone is not null");
            return (Criteria) this;
        }

        public Criteria andCTelephoneEqualTo(String value) {
            addCriterion("c_telephone =", value, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneNotEqualTo(String value) {
            addCriterion("c_telephone <>", value, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneGreaterThan(String value) {
            addCriterion("c_telephone >", value, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("c_telephone >=", value, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneLessThan(String value) {
            addCriterion("c_telephone <", value, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneLessThanOrEqualTo(String value) {
            addCriterion("c_telephone <=", value, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneLike(String value) {
            addCriterion("c_telephone like", value, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneNotLike(String value) {
            addCriterion("c_telephone not like", value, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneIn(List<String> values) {
            addCriterion("c_telephone in", values, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneNotIn(List<String> values) {
            addCriterion("c_telephone not in", values, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneBetween(String value1, String value2) {
            addCriterion("c_telephone between", value1, value2, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCTelephoneNotBetween(String value1, String value2) {
            addCriterion("c_telephone not between", value1, value2, "cTelephone");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteIsNull() {
            addCriterion("c_personal_website is null");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteIsNotNull() {
            addCriterion("c_personal_website is not null");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteEqualTo(String value) {
            addCriterion("c_personal_website =", value, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteNotEqualTo(String value) {
            addCriterion("c_personal_website <>", value, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteGreaterThan(String value) {
            addCriterion("c_personal_website >", value, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("c_personal_website >=", value, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteLessThan(String value) {
            addCriterion("c_personal_website <", value, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteLessThanOrEqualTo(String value) {
            addCriterion("c_personal_website <=", value, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteLike(String value) {
            addCriterion("c_personal_website like", value, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteNotLike(String value) {
            addCriterion("c_personal_website not like", value, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteIn(List<String> values) {
            addCriterion("c_personal_website in", values, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteNotIn(List<String> values) {
            addCriterion("c_personal_website not in", values, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteBetween(String value1, String value2) {
            addCriterion("c_personal_website between", value1, value2, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCPersonalWebsiteNotBetween(String value1, String value2) {
            addCriterion("c_personal_website not between", value1, value2, "cPersonalWebsite");
            return (Criteria) this;
        }

        public Criteria andCCompanyIsNull() {
            addCriterion("c_company is null");
            return (Criteria) this;
        }

        public Criteria andCCompanyIsNotNull() {
            addCriterion("c_company is not null");
            return (Criteria) this;
        }

        public Criteria andCCompanyEqualTo(String value) {
            addCriterion("c_company =", value, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyNotEqualTo(String value) {
            addCriterion("c_company <>", value, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyGreaterThan(String value) {
            addCriterion("c_company >", value, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("c_company >=", value, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyLessThan(String value) {
            addCriterion("c_company <", value, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyLessThanOrEqualTo(String value) {
            addCriterion("c_company <=", value, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyLike(String value) {
            addCriterion("c_company like", value, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyNotLike(String value) {
            addCriterion("c_company not like", value, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyIn(List<String> values) {
            addCriterion("c_company in", values, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyNotIn(List<String> values) {
            addCriterion("c_company not in", values, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyBetween(String value1, String value2) {
            addCriterion("c_company between", value1, value2, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCCompanyNotBetween(String value1, String value2) {
            addCriterion("c_company not between", value1, value2, "cCompany");
            return (Criteria) this;
        }

        public Criteria andCPositionIsNull() {
            addCriterion("c_position is null");
            return (Criteria) this;
        }

        public Criteria andCPositionIsNotNull() {
            addCriterion("c_position is not null");
            return (Criteria) this;
        }

        public Criteria andCPositionEqualTo(String value) {
            addCriterion("c_position =", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionNotEqualTo(String value) {
            addCriterion("c_position <>", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionGreaterThan(String value) {
            addCriterion("c_position >", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionGreaterThanOrEqualTo(String value) {
            addCriterion("c_position >=", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionLessThan(String value) {
            addCriterion("c_position <", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionLessThanOrEqualTo(String value) {
            addCriterion("c_position <=", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionLike(String value) {
            addCriterion("c_position like", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionNotLike(String value) {
            addCriterion("c_position not like", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionIn(List<String> values) {
            addCriterion("c_position in", values, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionNotIn(List<String> values) {
            addCriterion("c_position not in", values, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionBetween(String value1, String value2) {
            addCriterion("c_position between", value1, value2, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionNotBetween(String value1, String value2) {
            addCriterion("c_position not between", value1, value2, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCLocationIsNull() {
            addCriterion("c_location is null");
            return (Criteria) this;
        }

        public Criteria andCLocationIsNotNull() {
            addCriterion("c_location is not null");
            return (Criteria) this;
        }

        public Criteria andCLocationEqualTo(String value) {
            addCriterion("c_location =", value, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationNotEqualTo(String value) {
            addCriterion("c_location <>", value, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationGreaterThan(String value) {
            addCriterion("c_location >", value, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationGreaterThanOrEqualTo(String value) {
            addCriterion("c_location >=", value, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationLessThan(String value) {
            addCriterion("c_location <", value, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationLessThanOrEqualTo(String value) {
            addCriterion("c_location <=", value, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationLike(String value) {
            addCriterion("c_location like", value, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationNotLike(String value) {
            addCriterion("c_location not like", value, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationIn(List<String> values) {
            addCriterion("c_location in", values, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationNotIn(List<String> values) {
            addCriterion("c_location not in", values, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationBetween(String value1, String value2) {
            addCriterion("c_location between", value1, value2, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCLocationNotBetween(String value1, String value2) {
            addCriterion("c_location not between", value1, value2, "cLocation");
            return (Criteria) this;
        }

        public Criteria andCSignatureIsNull() {
            addCriterion("c_signature is null");
            return (Criteria) this;
        }

        public Criteria andCSignatureIsNotNull() {
            addCriterion("c_signature is not null");
            return (Criteria) this;
        }

        public Criteria andCSignatureEqualTo(String value) {
            addCriterion("c_signature =", value, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureNotEqualTo(String value) {
            addCriterion("c_signature <>", value, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureGreaterThan(String value) {
            addCriterion("c_signature >", value, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("c_signature >=", value, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureLessThan(String value) {
            addCriterion("c_signature <", value, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureLessThanOrEqualTo(String value) {
            addCriterion("c_signature <=", value, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureLike(String value) {
            addCriterion("c_signature like", value, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureNotLike(String value) {
            addCriterion("c_signature not like", value, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureIn(List<String> values) {
            addCriterion("c_signature in", values, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureNotIn(List<String> values) {
            addCriterion("c_signature not in", values, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureBetween(String value1, String value2) {
            addCriterion("c_signature between", value1, value2, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCSignatureNotBetween(String value1, String value2) {
            addCriterion("c_signature not between", value1, value2, "cSignature");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionIsNull() {
            addCriterion("c_personal_introduction is null");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionIsNotNull() {
            addCriterion("c_personal_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionEqualTo(String value) {
            addCriterion("c_personal_introduction =", value, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionNotEqualTo(String value) {
            addCriterion("c_personal_introduction <>", value, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionGreaterThan(String value) {
            addCriterion("c_personal_introduction >", value, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("c_personal_introduction >=", value, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionLessThan(String value) {
            addCriterion("c_personal_introduction <", value, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionLessThanOrEqualTo(String value) {
            addCriterion("c_personal_introduction <=", value, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionLike(String value) {
            addCriterion("c_personal_introduction like", value, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionNotLike(String value) {
            addCriterion("c_personal_introduction not like", value, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionIn(List<String> values) {
            addCriterion("c_personal_introduction in", values, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionNotIn(List<String> values) {
            addCriterion("c_personal_introduction not in", values, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionBetween(String value1, String value2) {
            addCriterion("c_personal_introduction between", value1, value2, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCPersonalIntroductionNotBetween(String value1, String value2) {
            addCriterion("c_personal_introduction not between", value1, value2, "cPersonalIntroduction");
            return (Criteria) this;
        }

        public Criteria andCAvatarIsNull() {
            addCriterion("c_avatar is null");
            return (Criteria) this;
        }

        public Criteria andCAvatarIsNotNull() {
            addCriterion("c_avatar is not null");
            return (Criteria) this;
        }

        public Criteria andCAvatarEqualTo(String value) {
            addCriterion("c_avatar =", value, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarNotEqualTo(String value) {
            addCriterion("c_avatar <>", value, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarGreaterThan(String value) {
            addCriterion("c_avatar >", value, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("c_avatar >=", value, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarLessThan(String value) {
            addCriterion("c_avatar <", value, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarLessThanOrEqualTo(String value) {
            addCriterion("c_avatar <=", value, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarLike(String value) {
            addCriterion("c_avatar like", value, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarNotLike(String value) {
            addCriterion("c_avatar not like", value, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarIn(List<String> values) {
            addCriterion("c_avatar in", values, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarNotIn(List<String> values) {
            addCriterion("c_avatar not in", values, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarBetween(String value1, String value2) {
            addCriterion("c_avatar between", value1, value2, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andCAvatarNotBetween(String value1, String value2) {
            addCriterion("c_avatar not between", value1, value2, "cAvatar");
            return (Criteria) this;
        }

        public Criteria andNCoinIsNull() {
            addCriterion("n_coin is null");
            return (Criteria) this;
        }

        public Criteria andNCoinIsNotNull() {
            addCriterion("n_coin is not null");
            return (Criteria) this;
        }

        public Criteria andNCoinEqualTo(Integer value) {
            addCriterion("n_coin =", value, "nCoin");
            return (Criteria) this;
        }

        public Criteria andNCoinNotEqualTo(Integer value) {
            addCriterion("n_coin <>", value, "nCoin");
            return (Criteria) this;
        }

        public Criteria andNCoinGreaterThan(Integer value) {
            addCriterion("n_coin >", value, "nCoin");
            return (Criteria) this;
        }

        public Criteria andNCoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_coin >=", value, "nCoin");
            return (Criteria) this;
        }

        public Criteria andNCoinLessThan(Integer value) {
            addCriterion("n_coin <", value, "nCoin");
            return (Criteria) this;
        }

        public Criteria andNCoinLessThanOrEqualTo(Integer value) {
            addCriterion("n_coin <=", value, "nCoin");
            return (Criteria) this;
        }

        public Criteria andNCoinIn(List<Integer> values) {
            addCriterion("n_coin in", values, "nCoin");
            return (Criteria) this;
        }

        public Criteria andNCoinNotIn(List<Integer> values) {
            addCriterion("n_coin not in", values, "nCoin");
            return (Criteria) this;
        }

        public Criteria andNCoinBetween(Integer value1, Integer value2) {
            addCriterion("n_coin between", value1, value2, "nCoin");
            return (Criteria) this;
        }

        public Criteria andNCoinNotBetween(Integer value1, Integer value2) {
            addCriterion("n_coin not between", value1, value2, "nCoin");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeIsNull() {
            addCriterion("d_create_time is null");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeIsNotNull() {
            addCriterion("d_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeEqualTo(Date value) {
            addCriterion("d_create_time =", value, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeNotEqualTo(Date value) {
            addCriterion("d_create_time <>", value, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeGreaterThan(Date value) {
            addCriterion("d_create_time >", value, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("d_create_time >=", value, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeLessThan(Date value) {
            addCriterion("d_create_time <", value, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("d_create_time <=", value, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeIn(List<Date> values) {
            addCriterion("d_create_time in", values, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeNotIn(List<Date> values) {
            addCriterion("d_create_time not in", values, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeBetween(Date value1, Date value2) {
            addCriterion("d_create_time between", value1, value2, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("d_create_time not between", value1, value2, "dCreateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeIsNull() {
            addCriterion("d_update_time is null");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeIsNotNull() {
            addCriterion("d_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeEqualTo(Date value) {
            addCriterion("d_update_time =", value, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeNotEqualTo(Date value) {
            addCriterion("d_update_time <>", value, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeGreaterThan(Date value) {
            addCriterion("d_update_time >", value, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("d_update_time >=", value, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeLessThan(Date value) {
            addCriterion("d_update_time <", value, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("d_update_time <=", value, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeIn(List<Date> values) {
            addCriterion("d_update_time in", values, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeNotIn(List<Date> values) {
            addCriterion("d_update_time not in", values, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("d_update_time between", value1, value2, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("d_update_time not between", value1, value2, "dUpdateTime");
            return (Criteria) this;
        }

        public Criteria andNStatusIsNull() {
            addCriterion("n_status is null");
            return (Criteria) this;
        }

        public Criteria andNStatusIsNotNull() {
            addCriterion("n_status is not null");
            return (Criteria) this;
        }

        public Criteria andNStatusEqualTo(Integer value) {
            addCriterion("n_status =", value, "nStatus");
            return (Criteria) this;
        }

        public Criteria andNStatusNotEqualTo(Integer value) {
            addCriterion("n_status <>", value, "nStatus");
            return (Criteria) this;
        }

        public Criteria andNStatusGreaterThan(Integer value) {
            addCriterion("n_status >", value, "nStatus");
            return (Criteria) this;
        }

        public Criteria andNStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_status >=", value, "nStatus");
            return (Criteria) this;
        }

        public Criteria andNStatusLessThan(Integer value) {
            addCriterion("n_status <", value, "nStatus");
            return (Criteria) this;
        }

        public Criteria andNStatusLessThanOrEqualTo(Integer value) {
            addCriterion("n_status <=", value, "nStatus");
            return (Criteria) this;
        }

        public Criteria andNStatusIn(List<Integer> values) {
            addCriterion("n_status in", values, "nStatus");
            return (Criteria) this;
        }

        public Criteria andNStatusNotIn(List<Integer> values) {
            addCriterion("n_status not in", values, "nStatus");
            return (Criteria) this;
        }

        public Criteria andNStatusBetween(Integer value1, Integer value2) {
            addCriterion("n_status between", value1, value2, "nStatus");
            return (Criteria) this;
        }

        public Criteria andNStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("n_status not between", value1, value2, "nStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}