package com.guo.technologyforum.dao.entity;

public class User_Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.n_id
     *
     * @mbg.generated
     */
    private Integer nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.n_user_id
     *
     * @mbg.generated
     */
    private Long nUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.n_role_id
     *
     * @mbg.generated
     */
    private Integer nRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.n_id
     *
     * @return the value of t_user_role.n_id
     *
     * @mbg.generated
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.n_id
     *
     * @param nId the value for t_user_role.n_id
     *
     * @mbg.generated
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.n_user_id
     *
     * @return the value of t_user_role.n_user_id
     *
     * @mbg.generated
     */
    public Long getnUserId() {
        return nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.n_user_id
     *
     * @param nUserId the value for t_user_role.n_user_id
     *
     * @mbg.generated
     */
    public void setnUserId(Long nUserId) {
        this.nUserId = nUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.n_role_id
     *
     * @return the value of t_user_role.n_role_id
     *
     * @mbg.generated
     */
    public Integer getnRoleId() {
        return nRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.n_role_id
     *
     * @param nRoleId the value for t_user_role.n_role_id
     *
     * @mbg.generated
     */
    public void setnRoleId(Integer nRoleId) {
        this.nRoleId = nRoleId;
    }
}